name: issue-workflow 1
on:
  # 일부 이벤트는 default branch에서만 트리거 된다.
  issues:
    types: [opened]

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action