name: multiple-event-workflow
on:
  # 여러개의 이벤트를 트리거로 설정할 때
  # push 할 때, issue open 될 때, 수동으로
  push:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action