name: artifact
on: push

jobs:
  uplodad-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        # hello.txt 파일에 hello-world 입력
        run: echo hello-world > hello.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-test
          path: ./hello.txt

  download-artifact:
    runs-on: ubuntu-latest
    # upload 후에 실행되어야 함
    needs: [uplodad-artifact]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-test
          path: ./
      - name: check
        run: cat hello.txt