name: context
on: workflow_dispatch

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        run: echo '${{ toJSON(github) }}'
      - name: check github context
        run: |
          echo ${{ githb.repository }}
          echo ${{ github.event_name }}