name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    # 2분 이상 실행되면 종료
    timeout-minutes: 2
    steps:
      - name: loop
        run: |
          count=0
          while true; do
            echo "seconds: $count"
            count=$((count+1))
            sleep 1
          done
        # 1분 이상 실행되면 종료
        timeout-minutes: 1
      - name: echo
        run: echo hello